name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11,14,17]
    steps:
      - uses: actions/checkout@v4
      # details https://github.com/actions/setup-java
      - name: Set up JDK  ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version:  ${{ matrix.jdk }}
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn -e --batch-mode package
  Publish:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      # details https://github.com/actions/setup-java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version:  11
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: mvn --batch-mode -DuseGitHubPackages=true deploy
